name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
    services:
      postgres:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v1
      - name: Setup php
        uses: shivammathur/setup-php@1.6.0
        with:
          php-version: ${{ matrix.php  }}
          extension-csv: dom, mbstring, mongodb
          coverage: xdebug
      - name: Show php version
        run: php${{ matrix.php }} -v && composer -V && php -m
      - name: Install dependencies
        run: composer install
      - name: Run database migrations
        run: |
          php${{ matrix.php }} artisan migrate
        env:
          DB_HOST: 0.0.0.0
          DB_PORT: 27017
          DB_CONNECTION: mongodb
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DATABASE: application
      - name: Run test console command
        run:
          php artisan geo:index
